# Generated by Django 2.2.7 on 2019-12-09 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0004_member_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('mobile', models.CharField(db_index=True, max_length=13)),
                ('student_donation', models.DecimalField(decimal_places=2, max_digits=6)),
                ('general_donation', models.DecimalField(decimal_places=2, max_digits=6)),
                ('additional_info', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('publications', models.ManyToManyField(blank=True, to='people.Member')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ProgramType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
