# Generated by Django 2.2.7 on 2019-12-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_auto_20191123_2236'),
        ('events', '0002_auto_20191209_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geography.Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programtype',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geography.Branch'),
            preserve_default=False,
        ),
    ]
