# Generated by Django 2.2.7 on 2019-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191209_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='general_donation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='program',
            name='place',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='student_donation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
