# Generated by Django 2.2.7 on 2019-12-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matirbank', '0002_auto_20191219_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='matirbank',
            name='money_receipt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
