# Generated by Django 2.2.7 on 2019-12-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matirbank', '0004_bankhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankhistory',
            options={'verbose_name_plural': 'Bank Histories'},
        ),
    ]
