# Generated by Django 2.2.7 on 2019-12-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0003_auto_20191123_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantum_associate_prefix', models.CharField(max_length=20, null=True, unique=True)),
                ('qa', models.IntegerField(default=0)),
                ('bank_code_prefix', models.CharField(max_length=20, null=True, unique=True)),
                ('bank_code', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.Branch')),
            ],
        ),
    ]
