# Generated by Django 2.2.7 on 2019-11-22 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('branch_type', models.CharField(blank=True, choices=[('BRANCH', 'Branch'), ('CELL', 'Cell'), ('PRECELL', 'Pre Cell')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('additional_info', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(blank=True, choices=[('BD', 'BD'), ('US', 'US')], max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
