# Generated by Django 2.2.7 on 2019-11-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_auto_20191122_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
    ]
