# Generated by Django 2.2.7 on 2019-11-22 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0002_auto_20191122_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('member_type', models.CharField(blank=True, choices=[('QMP', 'QMP'), ('QG', 'QG'), ('QA', 'QA')], max_length=20)),
                ('registration_no', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('OTR', 'Others')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(db_index=True, max_length=13)),
                ('address_1', models.CharField(blank=True, max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('marital_status', models.CharField(blank=True, choices=[('UNMARRIED', 'Single / Never Married'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated'), ('WIDOWED', 'Widowed')], max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('reference_name', models.CharField(max_length=150)),
                ('additional_info', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.Branch')),
            ],
        ),
    ]
