# Generated by Django 2.2.7 on 2019-12-31 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_member_is_quantier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FOR_SADAKAION', 'FOR_SADAKAION'), ('FOR_MATIR_BANK', 'FOR_MATIR_BANK'), ('FOR_GRADUATE_PROGRAM', 'FOR_GRADUATE_PROGRAM'), ('FOR_PROMASTER_PROGRAM', 'FOR_PROMASTER_PROGRAM'), ('FOR_OTHERS', 'FOR_OTHERS')], max_length=30)),
                ('feedback', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Member')),
            ],
        ),
    ]
